export const Headers = {
  dashboard: [
    { name: "ID", colId: "id", id: 0 },
    { name: "Stock Name", colId: "stockName", id: 1 },
    { name: "Average Price", colId: "avg", id: 2 },
    { name: "Quantity", colId: "quantity", id: 3 },
    { name: "Invested Value", colId: "totalInvested", id: 4 },
    // {name:"Current Value",colId:"currentValue",id:0},
    { name: "Buy Date", colId: "buyDate", id: 5 },
    { name: "Status", colId: "status", id: 6 },
    { name: "Info", colId: "info" },
    { name: "Edit", colId: "edit" },
  ],
  DashHeaders: [
    "name",
    "price_buy",
    "no_stocks",
    "invested",
    "price_sell",
    "returns",
    "profit_loss",
    "dividend",
    "tax_buy",
    "tax_sell",
    "net_return",
    "net_profit_loss",
    "net_profit_loss_percent",
    "buy_date",
    "sell_date",
    "status",
  ],
  IncomeTable: [
    { name: "Income Id", colId: "id", id: 0 },
    { name: "Income Type", colId: "incomeType", id: 1 },
    { name: "Amount", colId: "amount", id: 2 },
    { name: "Date", colId: "date", id: 3 },
    { name: "Created At", colId: "createdAt", id: 4 },
     { name: "Edit", colId: "edit" },
  ],
  IncomeTableHeaders: [
    "income_id",
    "income_type",
    "amount",
    "date",
    "created_at",
  ],
};
